### ISSUE TITLE
2Keys feature tracker

### ISSUE THREAD

**Issue by Gum-Joe** [Gum-Joe/2Keys#1]
Feature tracker for 2Keys

**v0.1.0**

- [ ] Implement direct to AHK execution
- [ ] Implement basic hotkey trigger
- [ ] Implement up keyboard events
- [ ] CLI:
   - [ ] Create detector
   - [ ] Get java cli download correct components (server with native addons) &  deps (AutoHotkey_H, NodeJS and install server deps)
   - [ ] Bundle required dependencies with the server (provide a ready made version) as either an exe + native addons or a bundled JS + native addon
   - [ ] Publish python detector on PyPi or create a setup shell script
   - [ ] Publish server an npm or setup Java CLI as alias to it (i.e. `2Keys server start` in java runs `node server.js`
- [ ] Block keystrokes to X-Server to prevent unintended execution on raspberry pi
- [ ] Write a detailed SETUP.md to help with setup & tidy README.md up
